// @generated by src/runtime/lower.ts from the delete-customer action-IR body.
// One implementation: this Rust is lowered from the same IR the interpreter
// runs, so the two BodyRef arms are equivalent by construction (drift corpus).
#[allow(warnings)]
mod bindings;

use bindings::app::caps::kv_store;
use bindings::app::caps::ui_state;
use bindings::app::caps::toast;
use bindings::exports::app::customer::delete_customer::{Guest, DeleteCustomerInput};

struct Component;

impl Guest for Component {
    fn invoke(input: DeleteCustomerInput) -> Result<(), String> {
        kv_store::delete("customers", "name", "eq", &json_str(&input.name))?;
        ui_state::set("state.confirmOpen", "false");
        toast::show(&format!("Deleted {}", input.name));
        Ok(())
    }
}

// Minimal JSON string encoder so filter/state values round-trip to the host
// as the exact Value (no serde dependency for the v0 string case).
fn json_str(s: &str) -> String {
    let mut o = String::from("\"");
    for c in s.chars() {
        match c {
            '"' => o.push_str("\\\""),
            '\\' => o.push_str("\\\\"),
            '\n' => o.push_str("\\n"),
            '\r' => o.push_str("\\r"),
            '\t' => o.push_str("\\t"),
            _ => o.push(c),
        }
    }
    o.push('"');
    o
}

bindings::export!(Component with_types_in bindings);
