package app:customer@0.1.0;

interface save-customer {
  record save-customer-input { name: string, email: string }
  invoke: func(input: save-customer-input) -> result<_, string>;
}

world save-customer-body {
  import app:caps/kv-store@0.1.0;
  import app:caps/toast@0.1.0;
  import app:caps/ui-state@0.1.0;
  export save-customer;
}
