// @generated by src/runtime/lower.ts from the save-customer action-IR body.
// One implementation: this Rust is lowered from the same IR the interpreter
// runs, so the two BodyRef arms are equivalent by construction (drift corpus).
#[allow(warnings)]
mod bindings;

use bindings::app::caps::kv_store;
use bindings::app::caps::toast;
use bindings::app::caps::ui_state;
use bindings::exports::app::customer::save_customer::{Guest, SaveCustomerInput};

struct Component;

impl Guest for Component {
    fn invoke(input: SaveCustomerInput) -> Result<(), String> {
        if input.name.trim().is_empty() {
            return Err("name is required".to_string());
        }
        kv_store::insert("customers", &[
            ("name".to_string(), input.name.clone()),
            ("email".to_string(), input.email.clone()),
        ])?;
        toast::show(&format!("Saved {}", input.name));
        ui_state::set("state.draftName", "\"\"");
        ui_state::set("state.draftEmail", "\"\"");
        Ok(())
    }
}

bindings::export!(Component with_types_in bindings);
